version: '3'

services:

  api_async:
    build: .
    container_name: api_async
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      postgres_async:
        condition: service_healthy

  postgres_async:
    container_name: postgres_async
    image: postgres:16.2-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_async
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U username"]
      interval: 2s
      timeout: 2s
      retries: 20
    restart: always

  adminer_async:
    image: adminer
    restart: always
    ports:
      - 8089:8080