version: '3'

services:

  api_async:
    build: .
    container_name: api_async
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql+asyncpg://username:password@postgresasync:5432/postgresasync"
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      postgresasync:
        condition: service_healthy

  postgresasync:
    container_name: postgresasync
    image: postgres:16.2-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresasync
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U username"]
      interval: 2s
      timeout: 2s
      retries: 20
    restart: always

  adminer_async:
    image: adminer
    restart: always
    ports:
      - 8089:8080