# syntax = docker/dockerfile:1.4

FROM python:3.9-slim 

WORKDIR /app

COPY requirements.txt ./

RUN apt-get update && apt-get install -y libpq-dev
RUN pip install --upgrade pip
RUN pip install psycopg2-binary 
RUN pip install "python-jose[cryptography]"
RUN pip install "passlib[bcrypt]"
RUN pip install -r requirements.txt

COPY ./app/ ./app

EXPOSE 8000

# Comando para iniciar o servidor FastAPI quando o contêiner for iniciado
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]