# syntax = docker/dockerfile:1.4

FROM python:3.9-slim 

WORKDIR /app

COPY requirements.txt ./

RUN apt-get update && apt-get install -y libpq-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY connect.py ./
