openapi: 3.0.0
info:
  title: Open Library API
  description: API para interagir com a Open Library
  version: 1.0.0
servers:
  - url: http://openlibrary.org
    description: Servidor principal da Open Library
paths:
  /people/{username}/lists/OL{list_id}/subjects:
    get:
      summary: Obter assuntos de uma lista
      description: Retorna os assuntos de uma lista específica.
      parameters:
        - name: username
          in: path
          description: Nome de usuário
          required: true
          schema:
            type: string
        - name: list_id
          in: path
          description: ID da lista
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Limite de resultados
          required: false
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /people/{username}/lists/OL{list_id}/editions:
    get:
      summary: Obter edições de uma lista
      description: Retorna as edições de uma lista específica.
      parameters:
        - name: username
          in: path
          description: Nome de usuário
          required: true
          schema:
            type: string
        - name: list_id
          in: path
          description: ID da lista
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Limite de resultados
          required: false
          schema:
            type: integer
            default: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Adicionar um seed a uma lista
      description: Adiciona um seed a uma lista específica.
      parameters:
        - name: username
          in: path
          description: Nome de usuário
          required: true
          schema:
            type: string
        - name: list_id
          in: path
          description: ID da lista
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                add:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /lists/OL{list_id}:
    get:
      summary: Ler uma lista
      description: Retorna informações sobre uma lista específica.
      parameters:
        - name: list_id
          in: path
          description: ID da lista
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    delete:
      summary: Excluir uma lista
      description: Exclui uma lista específica.
      parameters:
        - name: list_id
          in: path
          description: ID da lista
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
  /lists:
    post:
      summary: Criar uma nova lista
      description: Cria uma nova lista.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
  /search/lists:
    get:
      summary: Pesquisar listas
      description: Pesquisa listas com base em um termo de pesquisa.
      parameters:
        - name: q
          in: query
          description: Termo de pesquisa
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Limite de resultados
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Offset de resultados
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /people/{username}/lists:
    post:
      summary: Criar uma nova lista para um usuário
      description: Cria uma nova lista para um usuário específico.
      parameters:
        - name: username
          in: path
          description: Nome de usuário
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
  /people/{username}/lists.json:
    get:
      summary: Obter listas de um usuário
      description: Retorna todas as listas de um usuário.
      parameters:
        - name: username
          in: path
          description: Nome de usuário
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /people/{username}/lists/OL{list_id}/seeds:
    get:
      summary: Obter sementes de uma lista
      description: Retorna as sementes de uma lista específica.
      parameters:
        - name: username
          in: path
          description: Nome de usuário
          required: true
          schema:
            type: string
        - name: list_id
          in: path
          description: ID da lista
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /people/{username}/lists/OL{list_id}/seeds.json:
    get:
      summary: Obter sementes de uma lista (JSON)
      description: Retorna as sementes de uma lista específica em formato JSON.
      parameters:
        - name: username
          in: path
          description: Nome de usuário
          required: true
          schema:
            type: string
        - name: list_id
          in: path
          description: ID da lista
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
