from collections import Counter
import matplotlib.pyplot as plt

codes = [ 
"DNWADFEFUD",
"MBSZDYQBKPSK",
"WLUZVSVNVLEPZAV",
"REQXFXVZEQXYXTLTDFE",
"JWXTYFMQYWOWHYGWMYOM",
"QNBETIOEVCQAIRBINIKIIL",
"ALCDELPQWAOLDDLTNHLALNVNIWQVNCDENLHVN",
"QWKQCEBUUCFUTHQTKHQJQDJERQJUQJUGKUVKHQ",
"TIXKLBLMXGVBTXHVTFBGAHWHXQBMHFTLTITVBXGVBTXHLXZKXWHWHXJNBEBUKBH",
"OBEBODBEPUFNQPRVFNBQSFOEFBWJWFSPQSFTFOUFFODPOUSBBWFSEBEFJSBMJCFSEBEF",
"WNEPMLXDHXZEPEDHEZREATDRXREOTLGEKVNHTZREKELYOYRXREEMXJXTLTDFTRXITVDXRX",
"NSBEPNQRHZEVBANBRFGNRZFHNIRYBPVQNQRZNFRZFHNQRGREZVANPNBQRFRETHVENQVNAGR",
"ZUMOSZFWYXOEMJZMWVTZWXVYZBWHMSEFZFWXZVWXVYZFWTWOXEJZSZMFWVWONYEOZFEZJTW",
"QUFGUCHKQUFCXKFCUCQKPGXKVCKUOCUGPHTGPVCNQUEQOEQTCIGOPQUVQTPCKPXGPEKXGKU",
"ELZTMEMZJTEEOJCEMZZFKOKAOEWKJETETEMJSJFJRMZZNFKNGTETOEUYTZFJKUEQAENMKFARGJLEME",
"EQJQRQDTYQPLOVQYEKPILQKRKVZIYTJQJPRQVQPGEVPAPVILQCTGZKVTQXIPAQFPQRPYQGPVFPLOVQJQ",
"ZBTQHNRHCZCDRNAQDZUHCZDLSNCNRNRRDTRZRODBSNRBNMSHMTZRDMCNRDFQDCNCNRFQZMCDRBQHZCNQDR",
"AHTDNEGCAEGXMTGUHVODNPPDOFOHDJFDPFNDRJSXEACTUFGOEBEXMVNDMBUSEMQLMQCFTPRRSJVLVPSXETWDSBEREYGUCFOQAWKGAECVPFUVOBUDETGXRFFRRQGOOMGJAEQGECQQDBFHQVGHLFFHIYCSASQIUUWUO",
"PDDPAIPDZGSDGZFSBSPDPDUPEKZGUGXKBKXSAGVBGABGNKSDGUXSZKSXGNSDOGZGDDGPBPADOXMSEPDUGDDPGUGDDPBPZXKDSVSKABSGYKSAGFGVGNKVKMZGUGSQGPSABGADGNKVUPXOXGADYPXZGXCKOGDKZXKGVSEGEKBPABXKOG",
"VRUVAEUSYMGYGSUINKAFRVKEZKGQVRYSMMVPRXFHZAUFFXRGPTUWZEJXVUHIZHVVZDKPNIRSZAVVBJLRYIYUHIGIMUOXRQRGVLGTRWJSVKUQCVVIILKVZICLJZYYNWGSOMTGVECMYIJIFPZQDBKWRSMIMLGHRMISKCXTBWVHZMDMFXVRXQG",
"MZNQXCVQKIATMGHHPQVPXVEMHNLIYKWAMVLZMDNMWQJEBSPFQTXGZZMTXQAZIRGJCMVGTVZALRLEQQWFVSXLMGXVXQVNVEZXIPBIYKQNIVLKWZIVPMVQXVZAUBFIYBWFWMQQKVXMDIJRWSCQICTVLKMYXFCIZNLTPYCRGEDKWAJYTABNLHTIZVTW"
]

code2 = "DNWADFEFUD"
words = [
    "AMBICIOSOS",
"APRENDEMOS",
"ARTIFICIAL",
"ASSINATURA",
"CONSTRUCAO",
"EQUILIBRIO",
"FELICIDADE",
"HABILIDADE",
"IDENTIDADE",
"IGNORANCIA",
"ILUMINACAO",
"INCESSANTE",
"INCERTEZAS",
"INDIVIDUOS",
"INVISIVEIL",
"OBSTACULOS",
"PERMITINDO",
"RESULTADOS",
"REVELACOES",
"VELOCIDADE",
"VERDADEIRA"
]



for code in words:
    # Texto a ser analisado
    texto = code

    # Normalizando o texto (removendo espaços, pontuações e convertendo para minúsculas)
    texto = ''.join(filter(str.isalpha, texto)).lower()

    # Contando a frequência das letras
    frequencia = Counter(texto)

    # Separando as letras e os valores para o gráfico
    letras = list(frequencia.keys())
    valores = list(frequencia.values())

    # Plotando
    plt.figure(figsize=(10, 6))
    plt.bar(letras, valores, color='skyblue')
    plt.title('Frequência das Letras no Texto: ' + texto)
    plt.xlabel('Letras')
    plt.ylabel('Frequência')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
